strategy:
  # 最小市值限制：只选取市值大于10亿的股票
  min_mv: 1000000000
  # 净利润限制：只选取净利润为正的股票
  min_profit: 0
  # 营业收入限制：只选取营收大于1亿的股票
  min_revenue: 100000000
  # 牛市时持仓数（集中持股）
  hold_count_high: 5
  # 熊市或不确定行情时持仓数（分散持股）
  hold_count_low: 10
  # 调仓日：每周二（0=周一，1=周二，...）
  rebalance_weekday: 1
  # 调仓时间点：上午10点（格式为1000，单位为hhmm）
  rebalance_time: 1000
  # 动量周期：20个交易日（约等于1个月）
  momentum_days: 20
  # 单日下跌超过 -5% 触发熔断止损
  trend_threshold: -0.05
  # 小市值指数名称（用于动量与趋势判断），需与数据文件名匹配
  smallcap_index: ZZ2000
  # 对比的大盘指数列表（用于动量排序），需与数据文件名匹配
  large_indices:
    - HS300        # 沪深300
    - SH50         # 上证50
    - DividendETF  # 红利ETF