
model_name_or_path: /Users/dabai/work/data/llm_model/pre_model/time_series/AutonLab/MOMENT-1-small
#model_name_or_path: /Users/dabai/liepin/study/llm/Financial_QA/src/models/moment/forecast/outputs1
task_name: forecasting

seq_len: 128
patch_len: 8
patch_stride_len: 8
forecast_horizon: 16

head_dropout: 0.1
weight_decay: 0.0
freeze_encoder: true
freeze_embedder: true
freeze_head: false

train_data_path: /Users/dabai/liepin/study/llm/Financial_QA/data/zh_data/market
data_type: weekly
num_workers: 2
random_seed: 13
data_stride_len: 3

output_dir: "outputs/weekly"
num_train_epochs: 1
learning_rate: 1.0e-4
max_grad_norm: 2.0
per_device_train_batch_size: 16
warmup_ratio: 0.1
logging_steps: 10
save_strategy: "epoch"
eval_strategy: "epoch"
# load_best_model_at_end: true
# metric_for_best_model: "eval_mse"
# greater_is_better: false
