qlib_init:
    provider_uri: "/Users/dabai/liepin/study/llm/Financial_QA/data/qlib_data/zh_qlib"
    region: cn
market: &market csi300
logdir: &logdir output/patchtst
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2020-08-01
    fit_start_time: 2008-01-01
    fit_end_time: 2014-12-31
    instruments: *market


model_config: &model_config
  seq_len: 20
  pred_len: 1
  e_layers: 1
  factor: 3
  enc_in: 5
  patch_len: 5
  stride: 5
  c_out: 1
  d_model: 64
  d_ff: 64
  n_heads: 2
  dropout: 0.1
  activation: 'gelu'

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2017-01-01
        end_time: 2020-08-01
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5

task:
  model:
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
      logdir: *logdir
      loss: mse
      colsample_bytree: 0.8879
      learning_rate: 0.2
      subsample: 0.8789
      lambda_l1: 205.6999
      lambda_l2: 580.9768
      max_depth: 8
      num_leaves: 210
      num_threads: 20
  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
      segments:
        train: [ 2018-01-01, 2018-12-31 ]
        valid: [ 2019-01-01, 2019-12-31 ]
        test: [ 2020-01-01, 2020-12-31 ]
      seq_len: 20
      horizon: 1
      batch_size: 512


strategy_config: &strategy_config
  topk: 30
  hold_thre: 5
  commission_rate: 0.001
